// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm4jKksvYnw1FDLSTZenud5-iVJkaV9CI',
    appId: '1:521181472802:android:e03f18ccffbf25771fc27b',
    messagingSenderId: '521181472802',
    projectId: 'pixel-talk-62697',
    storageBucket: 'pixel-talk-62697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7wwm9bpMrt-XdlL84MlRc4foBXtCiQkE',
    appId: '1:521181472802:ios:ae9e93941624238f1fc27b',
    messagingSenderId: '521181472802',
    projectId: 'pixel-talk-62697',
    storageBucket: 'pixel-talk-62697.firebasestorage.app',
    androidClientId: '521181472802-3smq2rbgrjoh0huqgj26hcb0msit5dqr.apps.googleusercontent.com',
    iosClientId: '521181472802-r4r4rmqeiv9airl733821anqomodfqm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsChat',
  );

}